config/routes.rb
Rails.application.routes.draw do

  get '/' => "home#top"
  get 'about' => "users#about"

  resources :users
  resources :sessions
  resources :favorites, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{maximum: 30}
  validates :email, presence: true, length:{maximum: 255},format:{with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password, presence: true, length:{minimum: 6}

  before_validation{email.downcase!}
  has_secure_password
  mount_uploader :icon, ImageUploader
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    flash[:notice] = "お気に入りに登録しました"
    redirect_to pictures_url
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    flash[:notice] = "お気に入りから削除しました"
    redirect_to pictures_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :forcibly_redirect, only:[:new,:edit,:show,:destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    if @picture.save
      SubmitMailer.submit_mail(@picture).deliver
      flash[:notice] = "画像を投稿しました"
      redirect_to pictures_path
    else
      flash[:danger] = "画像の投稿に失敗しました"
      render 'new'
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      flash[:notice] = "編集しました"
      redirect_to pictures_path
    else
      flash[:danger] = "編集に失敗しました"
      render 'new'
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:notice] = "削除しました"
    redirect_to pictures_path
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:title,:content,:image,:image_cache)
  end

  def forcibly_redirect
    if current_user.present? == false
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインしました"
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user.id)
    else
      flash[:danger] = "ユーザー情報の更新が出来ませんでした"
      render 'edit'
    end
  end

  def about
    @favorite_pictures = current_user.favorite_pictures
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:icon,:icon_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="container">
<div class="description">
<img src="/back2.jpg">
<h2>内容</h2>
<p>勉強して学んだ内容をいちいち書くのは面倒です。そこでスクショをとって保存して学んだ内容をメモしていくものを作りました。</p>
</div>

<div class="how_to_use">
  <img src="/back3.jpg">
  <h2>使い方</h2>
  <ol>
    <li>まずは新規登録からアカウントを作成します</li>
    <li>↓</li>
    <li>アカウントを作成後、ログインします</li>
    <li>↓</li>
    <li>『スクショを保存』からタイトル、内容、画像を投稿します</li>
    <li>*投稿したものを見たいときは『スクショを確認』から確認します</li>
  </ol>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watepuphoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background_transparent">
    <div class="toggle">
      <span></span>
      <span></span>
      <span></span>
      <span>menu</span>
    </div>
    <div class="mobile_menu">
      <ul>
        <li><%= link_to "トップ", "/" %></li>
        <% if logged_in? %>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "投稿する", new_picture_path %></li>
          <li><%= link_to "一覧をみる", pictures_path %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_path %></li>
          <li><%= link_to "ログイン", new_session_path %></li>
        <% end %>
    </div>
    <header>
      <h1><%= link_to "わてぷフォト", "/" %></h1>
      <p>学んだことをメモしておけます</p>
    </header>

    <div class="slider">
    </div>

    <% flash.each do |key,value| %>
      <%= content_tag(:div, value, class:"#{key}") %>
    <% end %>

    <%= yield %>
    <footer>
      <p>2018 わてぷフォト</p>
    </footer>
  </div>
    <script>
    $(function(){
      $('.toggle').click(function(){
        $(this).toggleClass('active');

        if ($(this).hasClass('active')){
          $('.mobile_menu').addClass('active');
        }else{
          $('.mobile_menu').removeClass('active');
        }
      });
    });
    </script>
  </body>
</html>

app/views/pictures/confirm.html.erb
<h3>以下の内容で投稿します</h3>

<%= form_with(model: @picture, local: true) do |f| %>
  <div class="picture_form">
  <%= f.label :title %>
  </div>
  <div class="input_field">
  <%= f.text_field :title %>
  </div>

  <div class="picture_form">
  <%= f.label :image %>
  </div>
  <div class="picture_form">
  <%= image_tag(@picture.image.url) if @picture.image.url %>
  </div>
  <div class="input_field">
  <%= f.hidden_field :image_cache %>
  </div>

  <div class="picture_form">
  <%= f.label :content %>
  </div>
  <div class="input_field">
  <%= f.text_field :content %>
  </div>



  <%= f.submit "投稿する", :class => "submit_btn" %>

<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>

<%= form_with(model: @picture, local: true) do |f| %>
  <div class="picture_form">
  <%= f.label :title %>
  </div>
  <div class="input_field">
  <%= f.text_field :title %>
  </div>

  <div class="picture_form">
  <%= f.label :image %>
  </div>
  <div class="picture_form">
  <%= image_tag(@picture.image.url) if @picture.image.url %>
  </div>
  <div class="input_field">
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  </div>

  <div class="picture_form">
  <%= f.label :content %>
  </div>
  <div class="input_field">
  <%= f.text_field :content %>
  </div>



  <%= f.submit "投稿する", :class => "submit_btn" %>

<% end %>

app/views/pictures/index.html.erb
<h2>投稿一覧</h2>

<div class="picture_index">
<table>
  <tr>
    <th>アイコン</th>
    <th>タイトル</th>
    <th>画像</th>
    <th>内容</th>
    <th>詳細</th>
  </tr>

  <% @pictures.each do |pic| %>
  <tr>
    <td><%= image_tag(pic.user.icon.url) if pic.user.icon.url %></td>
    <td><%= pic.title %></td>
    <td><%= image_tag pic.image.url %></td>
    <td><%= pic.content %></td>
    <td><%= link_to "詳細を見る", picture_path(pic.id), class: "show_btn" %></td>
  </tr>
  <% end %>
</table>
</div>

<%= link_to "投稿する", new_picture_path, class: "picture_btn" %>

app/views/pictures/new.html.erb
<h2>新規投稿</h2>

<%= form_with(model: @picture, local: true) do |f| %>
  <div class="picture_form">
  <%= f.label :title %>
  </div>
  <div class="input_field">
  <%= f.text_field :title %>
  </div>

  <div class="picture_form">
  <%= f.label :image %>
  </div>
  <div class="picture_form">
  <%= image_tag(@picture.image.url) if @picture.image.url %>
  </div>
  <div class="input_field">
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  </div>

  <div class="picture_form">
  <%= f.label :content %>
  </div>
  <div class="input_field">
  <%= f.text_field :content %>
  </div>



  <%= f.submit "投稿する", :class => "submit_btn" %>

<% end %>

app/views/pictures/show.html.erb
<h2>詳細を見る</h2>

<div class="show_form">
<h3>タイトル</h3>
</div>
<div class="show_detail">
<%= @picture.title %>
</div>

<div class="show_form">
<h3>画像</h3>
</div>
<div class="show_detail">
<%= image_tag(@picture.image.url) if @picture.image.url %>
</div>

<div class="show_form">
<h3>内容</h3>
</div>
<div class="show_detail">
<%= @picture.content %>
</div>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to "お気に入り解除", favorite_path(id: @favorite.id), class: "delete_btn", method: :delete %>
  <% else %>
    <%= link_to "お気に入り登録", favorites_path(picture_id: @picture.id), class: "picture_btn", method: :post %>
  <% end %>
<% end %>

<%= link_to "編集する", edit_picture_path(@picture.id), class: "picture_btn" %>
<%= link_to "削除する", picture_path(@picture.id), class: "delete_btn",method: :delete %>

app/views/users/about.html.erb
<h2>お気に入り一覧</h2>

<div class="picture_index">
<table>
  <tr>
    <th>タイトル</th>
    <th>画像</th>
    <th>内容</th>
    <th>詳細</th>
  </tr>
<% @favorite_pictures.each do |pic| %>
  <tr>
    <td><%= pic.title %></td>
    <td><%= image_tag(pic.image.url) %></td>
    <td><%= pic.content %></td>
    <td><%= link_to "詳細を見る", picture_path(pic.id), class: "show_btn" %></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/edit.html.erb
<h2>編集</h2>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="user_form">
  <%= f.label :name %>
  </div>
  <div class="input_field">
  <%= f.text_field :name %>
  </div>

  <div class="user_form">
  <%= f.label :email %>
  </div>
  <div class="input_field">
  <%= f.email_field :email %>
  </div>

  <div class="user_form">
  <%= f.label :password %>
  </div>
  <div class="input_field">
  <%= f.password_field :password %>
  </div>

  <div class="user_form">
  <%= f.label :password_confirmation %>
  </div>
  <div class="input_field">
  <%= f.password_field :password_confirmation %>
  </div>

  <div class="user_form">
  <%= f.label :icon %>
  </div>
  <div class="user_form">
  <%= image_tag(@user.icon.url) if @user.icon.url %>
  </div>
  <div class="input_field">
  <%= f.file_field :icon %>
  <%= f.hidden_field :icon_cache %>
  </div>
</div>

  <%= f.submit "編集して登録", :class => "submit_btn" %>

<% end %>

app/views/users/new.html.erb
<h2>新規登録</h2>

<% @user.errors.any? %>
  <% @user.errors.full_messages.each do |m| %>
  <ul class="error_message">
    <li><%= m %></li>
  </ul>
  <% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="user_form">
  <%= f.label :name %>
  </div>
  <div class="input_field">
  <%= f.text_field :name %>
  </div>

  <div class="user_form">
  <%= f.label :email %>
  </div>
  <div class="input_field">
  <%= f.email_field :email %>
  </div>

  <div class="user_form">
  <%= f.label :password %>
  </div>
  <div class="input_field">
  <%= f.password_field :password %>
  </div>

  <div class="user_form">
  <%= f.label :password_confirmation %>
  </div>
  <div class="input_field">
  <%= f.password_field :password_confirmation %>
  </div>

  <div class="user_form">
  <%= f.label :icon %>
  </div>
  <div class="user_form">
  <%= image_tag(@user.icon.url) if @user.icon.url %>
  </div>
  <div class="input_field">
  <%= f.file_field :icon %>
  <%= f.hidden_field :icon_cache %>
  </div>

  <%= f.submit "新規登録", :class => "submit_btn" %>

<% end %>

app/views/users/show.html.erb
<div class="user_show">
<h2>マイページ</h2>

<div class="user_title">
  <h3>名前</h3>
</div>
<div class="user_detail">
  <p><%= @user.name %></p>
</div>

<div class="user_title">
  <h3>メールアドレス</h3>
</div>
<div class="user_detail">
  <p><%= @user.email %></p>
</div>

<div class="user_title">
  <h3>画像</h3>
</div>
<div class="user_detail">
  <p><%= image_tag(@user.icon.url) if @user.icon.url %></p>
</div>

  <%= link_to "ユーザー情報編集", edit_user_path, class: "edit_btn" %>
  <%= link_to "お気に入り一覧", about_path, class: "edit_btn" %>
</div>